

CREATE USER APP_USER
IDENTIFIED BY StrongPassword123
DEFAULT TABLESPACE gs_data      
TEMPORARY TABLESPACE gs_temp;

ALTER USER APP_USER QUOTA UNLIMITED ON GS_DATA;
ALTER USER APP_USER QUOTA UNLIMITED ON GS_INDEX;


GRANT CREATE SESSION TO APP_USER;        -- право подключаться к PDB
GRANT CREATE TABLE TO APP_USER;          -- создавать таблицы
GRANT CREATE SEQUENCE TO APP_USER;       -- создавать последовательности
GRANT CREATE PROCEDURE TO APP_USER;      -- создавать процедуры и пакеты
GRANT CREATE TRIGGER TO APP_USER;        -- триггеры (если нужны)
GRANT CREATE VIEW TO APP_USER;           
GRANT CREATE MATERIALIZED VIEW TO app_user;
GRANT EXECUTE ON DBMS_CRYPTO TO app_user;