ALTER SESSION set CONTAINER = KPDB_GAMESTORE;

CREATE PROFILE GUEST_PROFILE LIMIT
    SESSIONS_PER_USER      10
    FAILED_LOGIN_ATTEMPTS  UNLIMITED
    PASSWORD_LIFE_TIME     UNLIMITED
    PASSWORD_REUSE_TIME    1
    PASSWORD_REUSE_MAX     UNLIMITED;

CREATE PROFILE USER_PROFILE LIMIT
    SESSIONS_PER_USER      3
    FAILED_LOGIN_ATTEMPTS  5
    PASSWORD_LIFE_TIME     180
    PASSWORD_REUSE_TIME    30
    PASSWORD_REUSE_MAX     5;
    
CREATE PROFILE DEVELOPER_PROFILE LIMIT
    SESSIONS_PER_USER      10
    FAILED_LOGIN_ATTEMPTS  5
    PASSWORD_LIFE_TIME     90
    PASSWORD_VERIFY_FUNCTION ORA12C_VERIFY_FUNCTION;

CREATE PROFILE ADMIN_PROFILE LIMIT
    SESSIONS_PER_USER      1
    FAILED_LOGIN_ATTEMPTS  3
    PASSWORD_VERIFY_FUNCTION ORA12C_STRONG_VERIFY_FUNCTION
    PASSWORD_LIFE_TIME     60;



CREATE ROLE ROLE_GUEST;


CREATE ROLE ROLE_USER;


CREATE ROLE ROLE_DEVELOPER;


CREATE ROLE ROLE_ADMIN;




CREATE USER GUEST
    IDENTIFIED by guest_password
    PROFILE GUEST_PROFILE
    DEFAULT TABLESPACE GS_DATA
    TEMPORARY TABLESPACE GS_TEMP
    ACCOUNT UNLOCK;
    
    
CREATE USER USER_APP
    IDENTIFIED BY user_password
    PROFILE USER_PROFILE
    DEFAULT TABLESPACE GS_DATA
    TEMPORARY TABLESPACE GS_TEMP
    ACCOUNT UNLOCK;


CREATE USER DEVELOPER
    IDENTIFIED BY TEMP_password1
    DEFAULT TABLESPACE GS_DATA
    TEMPORARY TABLESPACE GS_TEMP
    PROFILE DEVELOPER_PROFILE
    ACCOUNT UNLOCK;

CREATE USER ADMIN
    IDENTIFIED BY TEMP_ADM_password12
    DEFAULT TABLESPACE GS_DATA
    TEMPORARY TABLESPACE GS_TEMP
    PROFILE ADMIN_PROFILE
    ACCOUNT UNLOCK;


GRANT CREATE SESSION TO ADMIN;
GRANT ALTER USER TO ADMIN;
GRANT CREATE USER TO ADMIN;
GRANT DROP USER TO ADMIN;
GRANT GRANT ANY PRIVILEGE TO ADMIN;
GRANT GRANT ANY ROLE TO ADMIN;
GRANT CREATE ANY TABLE TO ADMIN;
GRANT DROP ANY TABLE TO ADMIN;
GRANT CREATE ANY PROCEDURE TO ADMIN;
GRANT ALTER ANY PROCEDURE TO ADMIN;
GRANT DROP ANY PROCEDURE TO ADMIN;
GRANT UNLIMITED TABLESPACE TO ADMIN;



GRANT ROLE_GUEST TO GUEST;
ALTER USER GUEST DEFAULT ROLE ROLE_GUEST;

GRANT ROLE_USER TO USER_APP;
ALTER USER USER_APP DEFAULT ROLE ROLE_USER;

GRANT ROLE_DEVELOPER TO DEVELOPER;
ALTER USER DEVELOPER DEFAULT ROLE ROLE_DEVELOPER;

GRANT ROLE_ADMIN TO ADMIN;
ALTER USER ADMIN DEFAULT ROLE ROLE_ADMIN;

GRANT CREATE SESSION TO GUEST;
GRANT CREATE SESSION TO USER_APP;
GRANT CREATE SESSION TO DEVELOPER;
GRANT CREATE SESSION TO ADMIN;

